### ISSUE TITLE
Can't perform docker-compose up

### ISSUE THREAD

**Issue by f8al3rr** [owodunni/arbie#123]
ERROR: pull access denied for arbie, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Hello, I was wondering if this is intentional or just a bug. I was fascinated by your project but unfortunately couldn't run it.. 

Thanks in advance:)

**Comment by owodunni** [comment]
Sorry for a late answer. Missed this. You need to run the docker build command first.
